apiVersion: v1
kind: Secret
metadata:
  name: twiga-scan-secrets
  namespace: twiga-scan
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  POSTGRES_PASSWORD: <base64-encoded-postgres-password>
  REDIS_PASSWORD: <base64-encoded-redis-password>
  SECRET_KEY: <base64-encoded-secret-key>
  JWT_SECRET_KEY: <base64-encoded-jwt-secret>
  SENTRY_DSN: <base64-encoded-sentry-dsn>
stringData:
  # Non-base64 values for easier management
  DATABASE_URL: "postgresql://twiga_user:${POSTGRES_PASSWORD}@postgres-service:5432/twiga_scan"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis-service:6379/0" 