"""Initial schema

Revision ID: d498c24e9f66
Revises: 
Create Date: 2025-11-23 16:22:52.953056+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd498c24e9f66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.Column('certificate_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_domain'), 'providers', ['domain'], unique=False)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_index(op.f('ix_providers_public_key'), 'providers', ['public_key'], unique=False)
    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('BIP21', 'BOLT11', 'LNURL', 'LIGHTNING_ADDRESS', 'UNKNOWN', name='contenttype'), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('auth_status', sa.Enum('VERIFIED', 'SUSPICIOUS', 'INVALID', name='authstatus'), nullable=False),
    sa.Column('verification_results', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('user_action', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_logs_id'), 'scan_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scan_logs_scan_id'), 'scan_logs', ['scan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_logs_scan_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_id'), table_name='scan_logs')
    op.drop_table('scan_logs')
    op.drop_index(op.f('ix_providers_public_key'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_domain'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
